function J_thumb = get_J_thumb(in1)
%get_J_thumb
%    J_thumb = get_J_thumb(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Oct-2023 12:39:38

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t3.*(6.3e+1./2.0);
t6 = t4.*(6.3e+1./2.0);
t7 = -t6;
J_thumb = reshape([t7-sin(q1).*3.1e+1,t5+cos(q1).*3.1e+1,1.0,t7,t5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,14]);
